### ISSUE TITLE
Implementation of `Sum32()`

### ISSUE THREAD

**Issue by missinglink** [jmhodges/opposite_of_a_bloom_filter#11]
Heya, I was curious about your implementation of `Sum32()`.

What is the reason for left shifting 3 bits before adding the next byte?

It caught me by surprise because I assumed you were taking a 32 bit value from the first 4 of the 16 bytes returned by `m.Sum(nil)`, but in fact it's combining the bytes and presumably can only produce a number up to about 17 bits in length?

What is the benefit of doing this partial shift?

https://github.com/jmhodges/opposite_of_a_bloom_filter/blob/98e0396ff3753b77b6ff28fc2a08f8881d64b468/go/oppobloom/oppobloom.go#L59-L67

**Comment by jmhodges** [comment]
Unfortunately, I don't recall. Probably a bug but it's been 10 years.

**Comment by jmhodges** [comment]
It could have something to do with the sizeMask stuff used elsewhere, but I've not mathed it out
