### ISSUE TITLE
Feature request: May we have the feature to make the filter serializable ?

### ISSUE THREAD

**Issue by purplepapa** [jmhodges/opposite_of_a_bloom_filter#3]
Hi Jeff,

We need to persist it it to local storage or work with redis , could it be possible to add such feature?
There is some reference projects as follows:
1.https://github.com/Baqend/Orestes-Bloomfilter for redis
2.https://github.com/Cue/greplin-bloom-filter for file storage

Best regards,
Kevin Wen

**Comment by DivineTraube** [comment]
Hi, you are wrong about Redis. It is absolutely possible to do this in a thread-safe and consistent manner, as can be seen in our Bloom filter implementation. Commutativity, atomic MULTI blocks and optimistic locking in Redis make this perfectly possible.
