### ISSUE TITLE
What is the supposed error rate?

### ISSUE THREAD

**Issue by let4be** [jmhodges/opposite_of_a_bloom_filter#5]
If I know filter size and amount of stored items how can I calculate the probability of false negative?...
Thanks!
There is also a similar question how do I need to pickup a size if I have an estimation for amount of items I'm going to store

**Comment by rkq** [comment]
I think the the probability of false negative is very high. For example, if I have 100 elements, and set the size of filter to 10, for simplification, 10 elements will be hashed to one slot. If the 10 element sequence is *1, 2, 1, 2, 1, 2, 1, 2, 1, 2*。The *containsAndAdd* in java method will return *false, false, false, false, false,  false, false, false, false, false*, means all **negative**. The correct answer should be *false, false, true, true, true, true, true, true, true, true*. The error rate is **80%**! If you want to keep error rate low, this size of filter will be very large if you data set is large. This naive filter is useless in reality.

**Comment by jmhodges** [comment]
But data doesn't look like that in practice.

The error rare depends on the priors of your data. I don't have an analysis for you.
