### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by emirpasic** [jmhodges/opposite_of_a_bloom_filter#6]
I like the idea of this project and will find time to dig deeper into it.

For now I have just two small suggestions/corrections about the readme.

1) Correction in bold

> A Bloom filter is a data structure that may report it contains an item that it does not (a false positive), but is guaranteed to report correctly if it **does not contain** the item ("no false negatives"). 

2) Suggestion to add the link to the readme: https://www.somethingsimilar.com/2012/05/21/the-opposite-of-a-bloom-filter/

Cheers!

**Comment by jmhodges** [comment]
I think you've misread the README. That's describing a bloom filter and is correct.

**Comment by jmhodges** [comment]
Thanks for the input about adding a link! I'll consider it
