### ISSUE TITLE
Please add license

### ISSUE THREAD

**Issue by poikilos** [jmhodges/opposite_of_a_bloom_filter#8]
Hello, posting online gives you automatic copyright, and no license is most restrictive: <https://choosealicense.com/no-permission/>.

**Comment by poikilos** [comment]
if you are on github.com and click "add file" and name it license, you will automatically get a selection of licenses. Make sure you merge it with master (instead of creating a new branch) using the selection box above the "commit new file" button.

**Comment by jmhodges** [comment]
Done! (Also, as a reminder to myself, that lil trick only works if you type in a filename like "LICENSE" for the new file)

**Comment by poikilos** [comment]
Thanks
